# Bevezetés a `numpy` könyvtárba

`numpy` könyvtár importálása:

In [179]:
import numpy as np

### Tömbök létrehozása

Nézzük meg hogy hozzunk létre egy tömböt:

In [180]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


Emlékeztetőül, a lista bármilyen típusú elemt tartalmazhat. Ezzel szemben a `numpy` tömb csak azonos típusú elemeket tárolhat. A következő képpen tudjuk megnézni, hogy a tömb milyen típusú elemeket tárol:

In [181]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

int64


```{admonition} Kiegészítő anyag
:class: note
A listával szemben, mely láncolt listaként van megvalósítva, a `numpy` tömb folytonos memória területet használ. Mivel az elemek azonosak, így a tömb egy elemét annak indexe alapján könnyen meg lehet határozni a memóriában: például a 10-ik elem memóriában elfolgalt helyét úgy kapjuk meg, hogy a tömb típusának méretét 10-zel felszorozzuk. Ennek az adattárolésnak vannak előnyei és hátrányai is. Hasonlítsuk össze a tömböt a listával, hogy melyik előnyösebb a következő műveletek szempontjából: elem törlése, elem beszúrása, új elem hozzáadása.
```

Nézzünk egy példát, amikor szöveget tárolunk egy listában:

In [182]:
arr = np.array(['one', 'two', 'three', 'four', 'five'])
print(arr.dtype)

<U5


Egy másik példa `float` értékekkel:

In [183]:
arr = np.array([1.2, 2.1, 3.4, 4.1, 5.1])
print(arr.dtype)

float64


### Tömbök és dimenzióik

A tömbök sok szemponból hasonlítanak a matematikában tanult mátrixszokra. A tömböknek van dimenziója. Nézzünk példákat a különböző lehetőségekre:

Így hozzunk létre egy 0 dimenziós tömböt:

In [184]:
arr = np.array(5)
print(arr)

5


Vegyük észre, hogy nem használtunk `[]` zárójeleket. Ezzel szemben az 1 dimenziós tömb:

In [185]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


A 2 dimenziós tömbhöz két `[]` kapcsos zárójelet használunk:

In [186]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(type(arr))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


Nüzzük meg, hogy tudjuk a dimenziót és a méretet lekérdezni:

In [187]:
import numpy as np

a = np.array(42)
print(a.ndim)
print(a.shape)

b = np.array([1, 2, 3, 4, 5])
print(b.ndim)
print(b.shape)

c = np.array([[1, 2, 3], [4, 5, 6]])
print(c.ndim)
print(c.shape)

0
()
1
(5,)
2
(2, 3)


### Tömbök indexszelése

`numpy` tömböket a következő képpen indexszelhetünk:

In [188]:
a = np.array(42)
print(a)

b = np.array([1, 2, 3, 4, 5])
print(b[0])

c = np.array([[1, 2, 3], [4, 5, 6]])
print(c[0, 1]) 


42
1
2


Ez nagyon hasonlít a lista indexeléshez. De a tömb indexszelés szintaktikája különzik egy dimenziónál nagyobb tömbök esetén:

In [189]:
numbers = [[1, 2, 3], [4, 5, 6]]
print(numbers[0][1]) # lista indexszelése

numpy_array = np.array(numbers) 
print(numpy_array[0, 1]) # tömb indexszelése

2
2


### Iterálás tömbökön

Iterálás 1D listán:

In [190]:
b = np.array([1, 2, 3, 4, 5])
for k in range(b.shape[0]):
  print(b[k])

1
2
3
4
5


In [191]:
b = np.array([1, 2, 3, 4, 5])
for elem in b:
  print(elem)

1
2
3
4
5


Iteráljunk végig egy 2D tömbön:

In [192]:
numbers = np.array([[1, 2, 3], [4, 5, 6]])
for i in range(0, numbers.shape[0]):
  for j in range(0, numbers.shape[1]):
    print(numbers[i, j])

1
2
3
4
5
6


In [193]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
for row in arr_2d:
  print(row)
  for elem in row:
    print(elem)

[1 2 3]
1
2
3
[4 5 6]
4
5
6


### Szeletelés (slicing) tömbökön 

In [194]:
arr_1d = np.array([1, 2, 3, 4, 5])
print(arr_1d[2:4])
print(arr_1d[0:4])
print(arr_1d[:4]) # simplification of previous

print(arr_1d[-1]) # [-5, -4, -3, -2, -1]
print(arr_1d[-2])
print(arr_1d[-3:-1]) 
print(arr_1d[-3:]) 

print(arr_1d[0:5:2]) # start_index:end_index:step
print(arr_1d[0::2]) # automatically to the end, end_index=arr_1d.shape[0]
print(arr_1d[::2]) # automatically from start to the end, start_index=0, end_index=arr_1d.shape[0]

[3 4]
[1 2 3 4]
[1 2 3 4]
5
4
[3 4]
[3 4 5]
[1 3 5]
[1 3 5]
[1 3 5]


In [195]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d[0:2, 1:3]) 

[[2 3]
 [5 6]]


In [196]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]]) # 2 x 3
print(arr_2d) 
print()

print(arr_2d.reshape(3, 2)) 
print()

print(arr_2d.reshape(1, 6)) 
print()

print(arr_2d.reshape(3, -1)) 
print(arr_2d.reshape(-1, 3)) 

[[1 2 3]
 [4 5 6]]

[[1 2]
 [3 4]
 [5 6]]

[[1 2 3 4 5 6]]

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [197]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d.ndim)
print(arr_2d[0, 1])

arr_3d = arr_2d.reshape(2, -1, 3)
print(arr_3d.ndim) 
print(arr_3d[0, 0, 1])

2
2
3
2


### Sekély és mély másolás tömbökön

In [198]:
a = np.array([1, 2, 3, 4, 5])
b = a

a[1] = 100

print(a)
print(b)

[  1 100   3   4   5]
[  1 100   3   4   5]


In [199]:
a = np.array([1, 2, 3, 4, 5])

a_copy = a.copy() # mély másolás
a_view = a.view() # sekély másolás

a[1] = 100

print(a)
print(a_copy)
print(a_view)

[  1 100   3   4   5]
[1 2 3 4 5]
[  1 100   3   4   5]


### Tömbök összefűzése

Összefűzés `concatenate` segítségével:

In [200]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

con_arr = np.array([arr1, arr2])
print(con_arr)
print(con_arr.ndim)

conn_arr_2 = np.concatenate((arr1, arr2))
print(conn_arr_2)
print(conn_arr_2.ndim)

[[1 2 3]
 [4 5 6]]
2
[1 2 3 4 5 6]
1


In [201]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
conn_arr_2 = np.concatenate((arr1, arr2, arr1))
print(conn_arr_2)


[1 2 3 4 5 6 1 2 3]


In [202]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]]) # 2 x 3
print(np.concatenate((arr_2d, arr_2d))) # 4 x 3

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


Összefűzés adott dimenzió (tengely) mentén:

In [203]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]]) # 2 x 3
print(np.concatenate((arr_2d, arr_2d), axis=1)) # 2 x 6
print(np.concatenate((arr_2d, arr_2d), axis=0)) # 4 x 3

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [204]:
arr_3d = np.array([[1, 2, 3], [4, 5, 6]]).reshape(2, -1, 3) # 2 x 1 x 3
con_arr = np.concatenate((arr_3d, arr_3d), axis=1) # 2 x 2 x 3
print(con_arr)
print(con_arr[0, 0, 1])
print(con_arr[0, 1, 1])

[[[1 2 3]
  [1 2 3]]

 [[4 5 6]
  [4 5 6]]]
2
2


Horizontális és vertikális összefűzés `vstack` és `hstack` segítségével:

In [205]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]]) # 2 x 3
print(np.vstack((arr_2d, arr_2d)))  # 4 x 3
print(np.hstack((arr_2d, arr_2d)))  # 2 x 6

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


## Matematikai függvények `numpy` könyvtárral

In [206]:
import numpy as np

Néhány hasznos függvény a könyvtárból

In [207]:
v = np.array([0.1, 0.5, 0.8])
print(np.sin(v))
print(np.round(v))
print(np.sum(v))
print(np.diff(v))
print(np.degrees(v))
print(np.radians(v))

[0.09983342 0.47942554 0.71735609]
[0. 0. 1.]
1.4
[0.4 0.3]
[ 5.72957795 28.64788976 45.83662361]
[0.00174533 0.00872665 0.01396263]


Mátrixok létrehozása

In [208]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [209]:
i = np.eye(1,3)
print(i)

[[1. 0. 0.]]


In [210]:
Z = np.zeros(3)
print(Z)

[0. 0. 0.]


In [211]:
z = np.zeros((3,3))
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [212]:
v = np.array([1, 2, 3])
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
r = M @ v
print(r)

[14 32 50]


In [213]:
v = np.array([1, 2, 3])
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
r = M.T @ v
print(r)

[30 36 42]


Skalár szorzat:

In [214]:
v = np.array([1, 2, 3])
r = v.T @ v
print(r)

14


Diadikus szorzat:

In [215]:
v = np.array([1, 2, 3])
r = v @ v.T
print(r)

14


... ez így nem működik! Miért? 

In [216]:
v = np.array([[1, 2, 3]])
r = v.T @ v
print(r)

[[1 2 3]
 [2 4 6]
 [3 6 9]]


## Numerikus adatok beolvasása/írása szöveges fájból

In [217]:
data = np.loadtxt('./data/reg_interp/path.txt')

In [218]:
np.savetxt('output/path_comma.txt', data, delimiter=';')

In [219]:
np.savetxt('output/path_semicolon.txt', data, fmt='%.2f', delimiter=';')

Adjunk fejlécet a fájlhoz:

In [220]:
np.savetxt('output/path_header.txt', data, fmt='%.2f', delimiter=';', header='x [m];y [m]', comments='')

In [221]:
data = np.loadtxt('output/path_semicolon.txt', delimiter=';')

In [222]:
data_no_header = np.loadtxt('output/path_header.txt', delimiter=';', skiprows=1)
print(data.shape)
print(data_no_header.shape)

(25, 2)
(25, 2)
